name: 'Test, Build and Deploy'

on:

  pull_request:

  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup OpenJDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Show Google Chrome version
        run: $(which chrome) version

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 'latest'

      - name: Show lein version
        run: lein --version

      - name: Run application tests
        run: lein fig:test

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "metall-calc"
          heroku_email: ${{secrets.PERSONAL_EMAIL}}
          usedocker: true
